---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Harmony.
--- DateTime: 2022/12/22 22:50
---
-- 1.定义参数：优惠券ID、用户ID、库存key、订单key
-- 优惠券ID
local voucherId = ARGV[1]
-- 用户ID
local userId = ARGV[2]
-- 库存key(在Lua中拼接是用' .. ')
local stockKey = 'seckill:stock:' .. voucherId
-- 订单key
local orderKey = 'seckill:order' .. voucherId

-- 2.判断库存是否充足
if(tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足
    return 1
end

-- 3.判断用户是否下单(一人一单)
-- sismember判断成员元素是否是集合的成员
if(redis.call('sismember', orderKey, userId) == 1) then
    -- 重复下单
    return 2
end

-- 4.扣库存、下单
redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey, userId)
return 0